### ISSUE TITLE
Add Session middleware to Golang Server

### ISSUE THREAD

**Issue by joshblack** [abbeyhrt/keep-up-graphql#11]
@joshblack commented on [Thu Apr 19 2018](https://github.com/abbeyhrt/keep-up-old/issues/30)

The initial lifecycle of the session logic will be:

* A user makes a request to our Golang server
* We create a session middleware that is executed before all routes
* Inside the session middleware:
  * Check to see if a Cookie exists with the name `sid` (session id)
    * If it exists:
          * Fetch the user associated with the session (cookie value)
    * If it does not exist
      * Redirect to login page to create a new session
* Inside the Google callback handler
  * Create a cookie that associates the user to the session

**Comment by abbeyhrt** [comment]
This work will be done in two places: The session middleware and the google callback handler. 

*In the Handler:* 

- [x] The session is created 
- [x] Put into the sessions_table with the SID and userID
- [x] The session ID is then encoded for security

*In the middleware:* 

- [x] We will check to see if a cookie exists with the right name.
- [x]  If it doesn't, redirect user to login. 
- [x] If it does, decode the cookie value to get the SID
- [x] Use the decoded cookie value to get the associated userId. 
- [x] With the userID, find the rest of the info about the user and put it into the context so that the user information is available throughout the site.
